package org.example.maquinaPropia

fun main (){
    MaquinaCafe.makeCoffee(1.0)
    println("------------------------------")
    MaquinaCafe.makeCoffee(eleccion = 2)
    println("------------------------------")
    MaquinaCafe.makeCoffee()
    println("------------------------------")
    MaquinaCafe.makeCoffee(retirarVaso = true)
    println("------------------------------")
    MaquinaCafe.makeCoffee(1.0)
    println("------------------------------")
    MaquinaCafe.makeCoffee(eleccion = 2)
    println("------------------------------")
    MaquinaCafe.makeCoffee()
    println("------------------------------")
    MaquinaCafe.makeCoffee(retirarVaso = true)
    println("------------------------------")
    MaquinaCafe.makeCoffee(1.0)
    println("------------------------------")
    MaquinaCafe.makeCoffee(eleccion = 2)
    println("------------------------------")
    MaquinaCafe.makeCoffee()
    println("------------------------------")
    MaquinaCafe.makeCoffee(retirarVaso = true)
    println("------------------------------")
    MaquinaCafe.makeCoffee(1.0)
    println("------------------------------")
    MaquinaCafe.makeCoffee(eleccion = 2)
    println("------------------------------")
    MaquinaCafe.makeCoffee()
    println("------------------------------")
    MaquinaCafe.makeCoffee(retirarVaso = true)
    println("------------------------------")
    MaquinaCafe.makeCoffee(1.0)
    println("------------------------------")
    MaquinaCafe.makeCoffee(eleccion = 2)
    println("------------------------------")
    MaquinaCafe.makeCoffee()
    println("------------------------------")
    MaquinaCafe.makeCoffee(retirarVaso = true)
    println("------------------------------")
    MaquinaCafe.makeCoffee(1.0)
    println("------------------------------")
    MaquinaCafe.makeCoffee(eleccion = 2)
    println("------------------------------")
    MaquinaCafe.makeCoffee()
    println("------------------------------")
    MaquinaCafe.makeCoffee(retirarVaso = true)

    MaquinaCafe.makeCoffee(limpiar = true)
    println("------------------------------")
    MaquinaCafe.makeCoffee(1.0)
    println("------------------------------")
    MaquinaCafe.makeCoffee(eleccion = 2)
    println("------------------------------")
    MaquinaCafe.makeCoffee()
    println("------------------------------")
    MaquinaCafe.makeCoffee(retirarVaso = true)
    println("------------------------------")


}